### PR TITLE
Revert strange changes, +monthsTitle

### PR DESCRIPTION
**Pull request by hayk**
| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | no|yes
| BC breaks?      | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | MIT

### CODE REVIEW

**Comment by acrobat** [comment]
These changes were submitted in #1705. @tigranbalayan what do you think about this change?

**Comment by hayk** [comment]
@acrobat, I have used "standart" shortening for daysShort and monthsShort, which used in books and other open source products.
Array daysMin should contains 2-chars shortening instead of 3-chars shortening as in daysShort.

**Comment by acrobat** [comment]
Thanks @hayk, I will wait a few days to give @tigranbalayan some time to provide feedback. Otherwise I will merge this in a few days!

**Comment by hayk** [comment]
@acrobat, thanks!

**Comment by tigranbalayan** [comment]
Thanks @hayk @acrobat I mean it is ok to merge this change.

**Comment by acrobat** [comment]
Ok thanks @hayk and @tigranbalayan!

**Pull request merged**
