### PR TITLE
Added separateMonthYear option, changes datepicker-switch into two buttons

### PR DESCRIPTION
**Pull request by louiswheeleriv**
Added a new option called separateMonthYear (default false) which changes the single datepicker-switch button at the top into two buttons.  The button on the left, which displays the month, directs the user to the month selection mode.  The button on the right, which displays the year, directs the user to the year selection mode.

### CODE REVIEW

**Comment by acrobat** [comment]
Hi @louis-wheeler, thanks for the PR! Can you just cleanup some things
- Rebase the branch from the current master
- Revert the changes in the dist directory (we generate them from time to time in the master)

Thanks!

**Comment by louis-wheeler** [comment]
Reverted changes and re-applied work to files not in dist/ directory.  Rebased onto upstream master, should be up to date unless I slipped up somewhere.

**Comment by zhoujiealex** [comment]
@louiswheeleriv  any plan to accept this PR?
I use this awesome plugin in our project which is a JP UI.
The year/month's position of Japanese and Chinese is different from English.

Japan/Chinese:  <year><month> (2016年1月)
But English: <month><year> (January 2016)

So this feature is very import for non-English UI.

**Comment by zhoujiealex** [comment]
I try the latest 1.5.1, it seems this feature has already be included.
Thanks very much.

**Comment by lifejuggler** [comment]
@zhoujiealex how has this feature been added?

**Pull request closed without merging**
