### PR TITLE
Update Puppeteer

### PR DESCRIPTION
**Pull request by vsn4ik**

### CODE REVIEW

**Comment by vsn4ik** [comment]
@acrobat Good catch! Fixed 🙂

**Comment by acrobat** [comment]
Good job @vsn4ik! 

Just out of curiosity previously we used phantom-js, what is the advantage of puppeteer?

**Comment by vsn4ik** [comment]
https://phantomjs.org/ 
> PhantomJS development is suspended https://github.com/ariya/phantomjs/issues/15344

**Comment by acrobat** [comment]
Good to know! Btw thanks for your efforts on this library!

**Pull request merged**
