### PR TITLE
rename "vovember" to correct "november"

### PR DESCRIPTION
**Pull request by StefanKarlsson**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no|yes
| Related tickets | N/A
| License         | MIT

### CODE REVIEW

**Comment by vsn4ik** [comment]
@StefanKarlsson Thanks!

**Comment by StefanKarlsson** [comment]
Thank you @vsn4ik !

I see that it was a long time ago since we last had a release. Would it be possible to push a patch (1.8.1) so that we can update this dependency with npm? Or is a release planned in the near future?

**Comment by Necklaces** [comment]
Was it really necessary to make a new PR when #2437 already existed?

**Comment by StefanKarlsson** [comment]
@Necklaces No, it was not necessary. But I had already done the PR when I saw yours. I was sloppy and just checked for issues mentioning this and not PR:s. What matters is that it is now fixed :)

**Comment by Necklaces** [comment]
Right, so anyone can copy a PR, submit it as their own, smuggily claim it was due to sloppiness, and get the commit. Gotcha, good to know.

**Comment by StewPoll** [comment]
Any update on how long before 1.8.1 is released to npm?

**Pull request merged**
