### PR TITLE
Added large initial captital

### PR DESCRIPTION
**Pull request by OscarKolsrud**
| Q               | A
| --------------- | ---
| Bug fix?        no
| New feature?    no
| BC breaks?      no
| Related tickets 
| License         | MIT

### CODE REVIEW

**Comment by OscarKolsrud** [comment]
This only affects Norwegian

**Comment by Azaret** [comment]
@Nettsentrisk @OscarKolsrud Is there any official references saying that month and weekdays should be capitalized or not ?

**Comment by OscarKolsrud** [comment]
@Azaret No, there are not. But since they stand alone it makes so much more sense to have them capitalized than not. To make a difference between them, it looks so cluttered with everything in small letters. I prefer it capitalized rather than following the baselines

**Comment by Nettsentrisk** [comment]
This PR should be rejected, as Norwegian language rules dictate that these should be as they are currently implemented. Here is an explainer from the official Norwegian language council: https://www.sprakradet.no/sprakhjelp/Skriveregler/Stor_eller_liten_forbokstav/#dagar

**Pull request closed without merging**
