### PR TITLE
Use $.fn.css instead of $.fn.(show|hide)

### PR DESCRIPTION
**Pull request by stash86**
| Q               | A
| --------------- | ---
| Bug fix?        |yes
| New feature?    | no
| BC breaks?      | no
| License         | MIT

I'm using jQuery 3.x, and the popup windows just won't show. I looked around google, and found that the solution is just by changing .show() into .css('display','block'). Now it's working perfectly with jQuery 3.x. I have tested it with jQuery 1.12.4 and jQuery 2.2.4, and it's still working normally.

### CODE REVIEW

**Comment by vsn4ik** [comment]
@stash86 thanks for the PR!
Can you provide a jsfiddle to show the problem?
Thanks!

**Comment by stash86** [comment]
Sure, I'll try to create a jsFiddle to show the problem

**Comment by stash86** [comment]
Seems like my problem is a localized problem on my production site only. My localhost site and my jsfiddle shows no error using the original js file. You can delete this PR if you want.

**Comment by vsn4ik** [comment]
Thanks @stash86!

**Pull request closed without merging**
