### PR TITLE
Use defaults

### PR DESCRIPTION
**Pull request by steunix**
Make template use the default

### CODE REVIEW

**Comment by Azaret** [comment]
Make sense.
@steunix could you rebase your PR ?

**Comment by steunix** [comment]
Ok, I think it has been rebased.

**Comment by Azaret** [comment]
Can you check on `test/tests.html` ?
I think you have to fix the qunit test on templating.
At least there https://github.com/uxsolutions/bootstrap-datepicker/blob/master/tests/suites/options.js#L1528

**Comment by acrobat** [comment]
@steunix can you rebase the branch and check the failing test? Thanks!

**Pull request closed without merging**
