### PR TITLE
Fix for #2451

### LINKED ISSUE #2451: Datapicker shows in disabled fieldset
### Expected behaviour
When placed inside a disabled fieldset clicking the input add-on should not open the datepicker

### Actual behaviour
When placed inside a disabled fieldset clicking the input add-on opens the datepicker

### Datepicker version used
1.8.0

### Example code
```
<fieldset disabled>
    <div class="input-append date" id="datepicker">
        <input size="16" type="text" value="12-02-2012" readonly>
        <span class="add-on"><i class="icon-th"></i></span>
    </div>
<fieldset>
```

### PR DESCRIPTION
**Pull request by RobertSmits**
| Q               | A
| --------------- | ---
| Bug fix?        |yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | fixes #2451
| License         | MIT

### CODE REVIEW

**Comment by vsn4ik** [comment]
Thanks @RobertSmits!

**Comment by iguanaba** [comment]
Hello, not long ago I am using daterangepicker and I need to update the calendar based on a date that I receive per post after being initialized and running. How can I do this?
This code does not work for me

*******************************  START *****************************************************
<div class="col-md-2 text-center">
    <select id="perio" name="perio" class="input-sm form-control filtros">
       <option value="2018">2018</option>
       <option value="2019">2019</option>
    </select>
</div>
<div class="col-sm-3">
    <div class="input-daterange input-group" id="datepicker">
    <input type="text" class="form-control input-sm" readonly name="start" id="start" placeholder="desde" />
    <span class="input-group-addon"> a </span>
    <input type="text" class="form-control input-sm" readonly name="end" id="end" placeholder="hasta" />
    </div>
</div>

<script>
(function($){
var anio = $("#perio option:selected").val();
$('#start').val('01/01/' + anio);
$('#end').val('31/12/' + anio);
$('.input-daterange').datepicker({
	startDate: "01/01/" + anio,
	endDate: "31/12/" + anio,
	todayBtn: "linked",
	clearBtn: true,
	language: "es",
	autoclose: true,
	todayHighlight: true
});
$(document).on('change', '.filtros', function(){
     var valor = $(this).val();
    $('.input-daterange').datepicker('setStartDate', '20/01/2018');
    $('#start').val('01/01/' + valor); 
    $('#end').val('31/12/' + valor);
});
}(jQuery));  
</script>
********************************  END ****************************************************

I would appreciate it if you help me with this problem.
Thank you

**Comment by iguanaba** [comment]
I forward the code

`
<select id="perio" name="perio" class="input-sm form-control filtros">
<option value="2018">2018</option>
<option value="2019">2019</option>
</select>
<div class="col-sm-3">
 <div class="input-daterange input-group" id="datepicker">
<input type="text" class="form-control input-sm" readonly name="start" id="start" placeholder="desde" />
<span class="input-group-addon"> a </span>
<input type="text" class="form-control input-sm" readonly name="end" id="end" placeholder="hasta" />
</div>
</div>
<script>
(function($){

var anio = $("#perio option:selected").val();
$('#start').val('01/01/' + anio);
$('#end').val('31/12/' + anio);

$('.input-daterange').datepicker({
	startDate: "01/01/" + anio,
	endDate: "31/12/" + anio,
	todayBtn: "linked",
	clearBtn: true,
	language: "es",
	autoclose: true,
	todayHighlight: true
});
 $(document).on('change', '.filtros', function(){
    var valor = $(this).val();
    $('.input-daterange').datepicker('setStartDate', "01/01/" + $( "#perio option:selected" ).val());		 
    $('.input-daterange').datepicker('setEndDate', "31/12/" + $( "#perio option:selected" ).val());
    $('#start').val('01/01/' + valor); 
    $('#end').val('31/12/' + valor);
});
}(jQuery));  
</script>
`
Thanks !

**Comment by iguanaba** [comment]
Tengo un selector desde el cual envio el año seleccionado hascia el jquery para actualizar el calendario. Pero no funciona

**Pull request merged**
