### PR TITLE
Update addon selector for bootstrap 4

### LINKED ISSUE #2343: Fix compatibility issue with the final version of Bootstrap v4
Since they released bootstrap V4 beta 3, they changed the way we add "add-ons" on the input fields. Now we have two new classes: "prepend" and "append". Because of this, the datepicker is no longer working in some cases (for example, when I want to use an icon to open the calendar)... I don't have time to do all the process to make a pull request (create a branch, test and etc), but I fixed it myself with just a small change in the code. Here it goes (It's working):

Change this line:
  this.component = this.element.hasClass('date') ? this.element.find('.add-on, .input-group-addon, .btn') : false;

To this:
  this.component = this.element.hasClass('date') ? this.element.find('.prepend, .append, .add-on, .input-group-prepend, .input-group-append, .input-group-addon, .btn') : false;

Hope this helps.

### PR DESCRIPTION
**Pull request by jpknoll**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | fixes #2343
| License         | MIT

### CODE REVIEW

**Comment by jpknoll** [comment]
See also #1574

**Comment by EugenMayer** [comment]
Could that be merged somehow in the recent feature? Thank you for the work!

**Comment by vsn4ik** [comment]
Thanks @jpknoll!

**Comment by EugenMayer** [comment]
Thank you!

**Pull request merged**
